import type {
  ControlPlaneSummary,
  FleetBoardSnapshot,
  SystemNode,
  ToolAsset,
} from "./types";

export const systems: SystemNode[] = [
  {
    name: "jmcpd",
    role: "authority kernel",
    health: "nominal",
    jcp: "1.0.0",
    latency: "18ms",
    incident: {
      title: "Live control plane healthy",
      summary: "Core routing and replay are online.",
      quarantine: "None",
      drilldown: ["Open replay ledger", "Inspect approval challenges"],
    },
  },
  {
    name: "jeryu",
    role: "evidence runner",
    health: "watch",
    jcp: "1.0.0",
    latency: "42ms",
    incident: {
      title: "Evidence refresh lagging",
      summary: "A late evidence bundle keeps the tool graph in watch mode.",
      quarantine: "Read-only until the next evidence pass lands.",
      drilldown: ["Open ecosystem graph", "Inspect evidence bundle EV-732"],
    },
  },
  {
    name: "jankurai",
    role: "standards memory",
    health: "nominal",
    jcp: "1.0.0",
    latency: "25ms",
  },
  {
    name: "mcp-bridge",
    role: "quarantined adapter",
    health: "blocked",
    jcp: "adapter",
    latency: "n/a",
    incident: {
      title: "Write lease withheld",
      summary: "The bridge stays blocked until it has a service card and evidence bundle.",
      quarantine: "Keep it read-only.",
      drilldown: ["Open work order WO-1043", "Open adapter service card"],
    },
  },
];

export const toolAssets: ToolAsset[] = [
  {
    name: "repo.apply_patch",
    className: "code mutation",
    conformance: "C2 native",
    sideEffects: "workspace write",
    dataClasses: ["source", "diff"],
    repo: "JMCP",
    provider: "codex",
    health: "nominal",
    dependsOn: ["jeryu.repo.adopt", "jankurai.diff-audit"],
    queue: 1,
  },
  {
    name: "ci.run_lane",
    className: "evidence",
    conformance: "C1 constrained",
    sideEffects: "compute spend",
    dataClasses: ["logs", "artifacts"],
    repo: "JMCP",
    provider: "jeryu",
    health: "watch",
    dependsOn: ["jeryu.checks.status", "jankurai.proof"],
    queue: 2,
  },
  {
    name: "store.query_lessons",
    className: "memory read",
    conformance: "C2 native",
    sideEffects: "none",
    dataClasses: ["lessons", "policy"],
    repo: "jankurai",
    provider: "jankurai",
    health: "nominal",
    dependsOn: ["jeryu.evidence.bundle"],
    queue: 0,
  },
  {
    name: "jeryu.repo.adopt",
    className: "repository governance",
    conformance: "C1 constrained",
    sideEffects: "local git remote",
    dataClasses: ["repo", "policy"],
    repo: "Jeryu",
    provider: "jeryu",
    health: "watch",
    dependsOn: ["git.remote", "jeryu.api.health"],
    queue: 1,
  },
  {
    name: "jeryu.evidence.bundle",
    className: "evidence",
    conformance: "C2 native",
    sideEffects: "artifact write",
    dataClasses: ["logs", "hashes", "checks"],
    repo: "Jeryu",
    provider: "jeryu",
    health: "nominal",
    dependsOn: ["ci.run_lane"],
    queue: 0,
  },
  {
    name: "jekko.run_headless",
    className: "worker execution",
    conformance: "C1 leased",
    sideEffects: "tool calls",
    dataClasses: ["prompt", "diff", "logs"],
    repo: "Jekko",
    provider: "jekko",
    health: "degraded",
    dependsOn: ["lease.validate", "jeryu.evidence.bundle"],
    queue: 0,
  },
];

export const controlPlane: ControlPlaneSummary = {
  generatedAt: "fixture",
  eventWatermark: 42,
  eventBus: {
    appendOnly: true,
    streamUrl: "/events",
    sources: ["runnerd", "agent_sessions", "ci_lanes", "audit_lanes"],
  },
  repos: [
    {
      name: "JMCP",
      health: "nominal",
      currentVersion: "0.1.0",
      lastSuccessfulMainCi: "sha256:ci-main",
      lastBinary: "sha256:jmcpd",
      lastTests: "sha256:test",
      latestChangedFiles: ["crates/jmcp-app/src/control_plane.rs"],
      activeWorkcells: 1,
      overdueActivity: false,
      stuckActivity: false,
      failingAudit: false,
      auditReason: null,
      rerunCommand: "just jankurai-local",
    },
    {
      name: "Jankurai",
      health: "watch",
      currentVersion: "0.1.0",
      lastSuccessfulMainCi: null,
      lastBinary: null,
      lastTests: "sha256:jankurai-proof",
      latestChangedFiles: ["agent/audit-policy.toml"],
      activeWorkcells: 1,
      overdueActivity: false,
      stuckActivity: false,
      failingAudit: true,
      auditReason: "No recent audit, CI, or proof evidence observed.",
      rerunCommand: "just score",
    },
  ],
  activeWorkcells: [
    {
      id: "jmcp-microtask-jankurai.changed-path-audit",
      repo: "Jankurai",
      agent: "jmcp.microtask_planner",
      task: "jankurai.diff-audit",
      status: "submitted",
      allowedSlice: ["Jankurai"],
      persistence: "pr_export_only",
      pty: "pty_disabled",
      updatedAt: "fixture",
      overdue: false,
      stuck: false,
      rerunCommand: "just score",
    },
  ],
  auditLanes: [
    {
      repo: "JMCP",
      lane: "jankurai.policy",
      health: "nominal",
      reason: "Latest audit evidence is visible to JMCP.",
      latestEvidence: "sha256:ci-main",
      rerunCommand: "just jankurai-local",
    },
    {
      repo: "Jankurai",
      lane: "jankurai.policy",
      health: "watch",
      reason: "No recent audit, CI, or proof evidence observed.",
      latestEvidence: null,
      rerunCommand: "just score",
    },
  ],
  policy: {
    sandboxRequired: true,
    directPersistenceAllowed: false,
    prExportRequired: true,
    ptyDefault: "disabled_unless_interactive",
    findingCount: 1,
  },
  versioning: {
    current: "0.1.0",
    recommended: "0.1.1",
    impact: "patch",
    reason: "Patch-safe evidence or maintenance work was observed.",
    releaseCompatible: true,
    rollbackCompatible: true,
  },
  streams: [
    {
      name: "jmcp.events",
      url: "/events",
      stdoutStderr: false,
      ptyInput: false,
      interactiveOnly: false,
    },
    {
      name: "session.stdout-stderr",
      url: "/jitux/sessions/:id/stream",
      stdoutStderr: true,
      ptyInput: false,
      interactiveOnly: false,
    },
    {
      name: "session.pty",
      url: "/jitux/sessions/:id/ws",
      stdoutStderr: true,
      ptyInput: true,
      interactiveOnly: true,
    },
  ],
};

export const fleetBoard: FleetBoardSnapshot = {
  generatedAtNote: "veox.ai universe board (fixture snapshot).",
  schema: "fleet-board.schema.md",
  repos: [
    {
      name: "jeryu",
      path: "/home/ubuntu/jeryu",
      branch: "main",
      host: "forge",
      dirty: 26,
      dirtyFiles: 26,
      lastCommitSha: "87e4ca9",
      headSha: "87e4ca95ea63412dda31acc70b337a184c2eca16",
      lastCommitWhen: "4 hours ago",
      lastCommitEpoch: 1710000000,
      lastBinaryEpoch: 1710000100,
      lastTestsEpoch: 1709990000,
      version: "4.0.0",
      ciConfigured: true,
      score: 64,
      raw: null,
      caps: [],
      capsCount: null,
      hardFindings: 29,
      hlLevel: "HL0",
      scoreSource: "fleet-jeryu.json",
      scoreFreshness: "outdated",
      activeRunnerCount: 20,
      runnerBusy: true,
      runnerHint: "20 local runners, 1 recently busy",
      mainCiAgeSeconds: 3600,
      jeryuGate: "green",
      artifactState: {
        local: "present",
        devCanary: "present",
        prod: "present",
        release: "present",
        promote: "present",
        latestSha: "87e4ca95ea63412dda31acc70b337a184c2eca16",
      },
      topFindings: ["workspace version pin remains", "literal version sweep still pending"],
      topToolOpportunities: ["jeryu-wsversion", "inherit-guard ratchet"],
    },
    {
      name: "jankurai",
      path: "/home/ubuntu/jankurai",
      branch: "claude/jankurai-consolidated",
      host: "forge",
      dirty: 0,
      dirtyFiles: 0,
      lastCommitSha: "de19e08",
      headSha: "760335d3d2c0edf2b8c6fd56ea794df8f94a5bcb",
      lastCommitWhen: "42 minutes ago",
      lastCommitEpoch: 1710000200,
      lastBinaryEpoch: 1710000300,
      lastTestsEpoch: 1710000300,
      version: "1.6.10",
      ciConfigured: true,
      score: 96,
      raw: 96,
      caps: [],
      capsCount: 0,
      hardFindings: 0,
      hlLevel: "HL3",
      scoreSource: "inline",
      scoreFreshness: "fresh",
      activeRunnerCount: 20,
      runnerBusy: true,
      runnerHint: "20 local runners, 1 recently busy",
      mainCiAgeSeconds: 1200,
      jeryuGate: "green",
      artifactState: {
        local: "present",
        devCanary: "present",
        prod: "present",
        release: "present",
        promote: "present",
        latestSha: "760335d3d2c0edf2b8c6fd56ea794df8f94a5bcb",
      },
      topFindings: [],
      topToolOpportunities: [],
    },
    {
      name: "jmcp",
      path: "/home/ubuntu/jmcp",
      branch: "main",
      host: "forge",
      dirty: 1,
      dirtyFiles: 1,
      lastCommitSha: "e14fa01",
      headSha: "e14fa01",
      lastCommitWhen: "13 minutes ago",
      lastCommitEpoch: 1710000400,
      lastBinaryEpoch: null,
      lastTestsEpoch: null,
      version: "0.1.0",
      ciConfigured: true,
      score: null,
      raw: null,
      caps: [],
      capsCount: null,
      hardFindings: null,
      hlLevel: null,
      scoreSource: null,
      scoreFreshness: "unscored",
      activeRunnerCount: 20,
      runnerBusy: true,
      runnerHint: "20 local runners, 1 recently busy",
      mainCiAgeSeconds: null,
      jeryuGate: "missing-receipts",
      artifactState: {
        local: "missing",
        devCanary: "missing",
        prod: "missing",
        release: "missing",
        promote: "missing",
        latestSha: "e14fa01",
      },
      topFindings: ["control-plane stays live", "fleet-board ingest is read-only"],
      topToolOpportunities: ["cockpit Universe merge", "board-backed repo cards"],
    },
    {
      name: "jekko",
      path: "/home/ubuntu/jekko",
      branch: "main",
      host: "github",
      dirty: 1,
      dirtyFiles: 1,
      lastCommitSha: "83acce8c7",
      headSha: "83acce8c7",
      lastCommitWhen: "9 minutes ago",
      lastCommitEpoch: 1710000500,
      lastBinaryEpoch: 1710000500,
      lastTestsEpoch: 1710000500,
      version: "2.0.6",
      ciConfigured: true,
      score: 89,
      raw: 89,
      caps: [],
      capsCount: 0,
      hardFindings: 0,
      hlLevel: "HL2",
      scoreSource: "/tmp/jekko-final.json",
      scoreFreshness: "cached",
      activeRunnerCount: 20,
      runnerBusy: true,
      runnerHint: "20 local runners, 1 recently busy",
      mainCiAgeSeconds: 900,
      jeryuGate: "green",
      artifactState: {
        local: "present",
        devCanary: "present",
        prod: "present",
        release: "present",
        promote: "present",
        latestSha: "83acce8c7",
      },
      topFindings: ["mixed provenance in the live board"],
      topToolOpportunities: ["close the remaining git hygiene gap"],
    },
    {
      name: "jnoccio",
      path: "/home/ubuntu/jnoccio",
      branch: "ci/add-gitlab-ci",
      host: "forge",
      dirty: 20,
      dirtyFiles: 20,
      lastCommitSha: "0659b5b",
      headSha: "0659b5b",
      lastCommitWhen: "4 days ago",
      lastCommitEpoch: 1709900000,
      lastBinaryEpoch: 1709900100,
      lastTestsEpoch: 1709900200,
      version: "1.1.0",
      ciConfigured: true,
      score: 72,
      raw: 72,
      caps: ["delivery-lane"],
      capsCount: 1,
      hardFindings: 2,
      hlLevel: "HL1",
      scoreSource: "fleet-jnoccio.json",
      scoreFreshness: "cached",
      activeRunnerCount: 20,
      runnerBusy: true,
      runnerHint: "20 local runners, 1 recently busy",
      mainCiAgeSeconds: 86400,
      jeryuGate: "missing-receipts",
      artifactState: {
        local: "missing",
        devCanary: "missing",
        prod: "missing",
        release: "missing",
        promote: "missing",
        latestSha: "0659b5b",
      },
      topFindings: ["GitLab CI branch still needs owner direction"],
      topToolOpportunities: ["normalize the delivery lane"],
    },
  ],
  totals: {
    repoCount: 5,
    audited: 4,
    failed: 0,
    minScore: 64,
    maxScore: 96,
    averageScore: 80.25,
    totalHardFindings: 31,
    belowThreshold: 0,
  },
  errors: [],
};
