import type {
  SystemNode,
  ToolAsset,
} from "./types";

export const systems: SystemNode[] = [
  {
    name: "jmcpd",
    role: "authority kernel",
    health: "nominal",
    jcp: "1.0.0",
    latency: "18ms",
    incident: {
      title: "Live control plane healthy",
      summary: "Core routing and replay are online.",
      quarantine: "None",
      drilldown: ["Open replay ledger", "Inspect approval challenges"],
    },
  },
  {
    name: "jeryu",
    role: "evidence runner",
    health: "watch",
    jcp: "1.0.0",
    latency: "42ms",
    incident: {
      title: "Evidence refresh lagging",
      summary: "A late evidence bundle keeps the tool graph in watch mode.",
      quarantine: "Read-only until the next evidence pass lands.",
      drilldown: ["Open ecosystem graph", "Inspect evidence bundle EV-732"],
    },
  },
  {
    name: "jankurai",
    role: "standards memory",
    health: "nominal",
    jcp: "1.0.0",
    latency: "25ms",
  },
  {
    name: "mcp-bridge",
    role: "quarantined adapter",
    health: "blocked",
    jcp: "adapter",
    latency: "n/a",
    incident: {
      title: "Write lease withheld",
      summary: "The bridge stays blocked until it has a service card and evidence bundle.",
      quarantine: "Keep it read-only.",
      drilldown: ["Open work order WO-1043", "Open adapter service card"],
    },
  },
];

export const toolAssets: ToolAsset[] = [
  {
    name: "repo.apply_patch",
    className: "code mutation",
    conformance: "C2 native",
    sideEffects: "workspace write",
    dataClasses: ["source", "diff"],
    repo: "JMCP",
    provider: "codex",
    health: "nominal",
    dependsOn: ["jeryu.repo.adopt", "jankurai.diff-audit"],
    queue: 1,
  },
  {
    name: "ci.run_lane",
    className: "evidence",
    conformance: "C1 constrained",
    sideEffects: "compute spend",
    dataClasses: ["logs", "artifacts"],
    repo: "JMCP",
    provider: "jeryu",
    health: "watch",
    dependsOn: ["jeryu.checks.status", "jankurai.proof"],
    queue: 2,
  },
  {
    name: "store.query_lessons",
    className: "memory read",
    conformance: "C2 native",
    sideEffects: "none",
    dataClasses: ["lessons", "policy"],
    repo: "jankurai",
    provider: "jankurai",
    health: "nominal",
    dependsOn: ["jeryu.evidence.bundle"],
    queue: 0,
  },
  {
    name: "jeryu.repo.adopt",
    className: "repository governance",
    conformance: "C1 constrained",
    sideEffects: "local git remote",
    dataClasses: ["repo", "policy"],
    repo: "Jeryu",
    provider: "jeryu",
    health: "watch",
    dependsOn: ["git.remote", "jeryu.api.health"],
    queue: 1,
  },
  {
    name: "jeryu.evidence.bundle",
    className: "evidence",
    conformance: "C2 native",
    sideEffects: "artifact write",
    dataClasses: ["logs", "hashes", "checks"],
    repo: "Jeryu",
    provider: "jeryu",
    health: "nominal",
    dependsOn: ["ci.run_lane"],
    queue: 0,
  },
  {
    name: "jekko.run_headless",
    className: "worker execution",
    conformance: "C1 leased",
    sideEffects: "tool calls",
    dataClasses: ["prompt", "diff", "logs"],
    repo: "Jekko",
    provider: "jekko",
    health: "degraded",
    dependsOn: ["lease.validate", "jeryu.evidence.bundle"],
    queue: 0,
  },
];
