import type {
  AttentionPacket,
  ApprovalRequest,
  MemoryProposal,
  ReplayEvent,
  VoiceTextThread,
} from "./types";

export const attentionPackets: AttentionPacket[] = [
  {
    id: "AP-88",
    workOrderId: "WO-1043",
    attentionLevel: "incident",
    modality: "ui-card",
    summary: "Quarantine the bridge until the service card lands.",
    whyNow: "The adapter still lacks an evidence-backed write lease.",
    recommendation: "Keep the bridge read-only and collect the missing evidence first.",
    decisionNeeded: true,
    alternatives: [
      { id: "alt-1", label: "Keep read-only", effect: "limits blast radius", risk: "low" },
      { id: "alt-2", label: "Promote a narrower lease", effect: "still requires evidence", risk: "medium" },
    ],
    riskDelta: { from: "low", to: "high", note: "promoting early increases write exposure" },
    drilldown: [
      { label: "Open WO-1043", target: "work.WO-1043", kind: "work-order" },
      { label: "Open adapter card", target: "tools-data.jeryu.repo.adopt", kind: "tool-card" },
    ],
    expires: "6m",
    incident: {
      id: "INC-1043",
      title: "Adapter quarantine remains active",
      severity: "high",
      summary: "The bridge lacks a complete service card and should not gain writes.",
      quarantine: "Read-only until evidence is complete.",
      drilldown: ["Open work order WO-1043", "Open evidence bundle EV-732"],
    },
  },
  {
    id: "AP-89",
    workOrderId: "WO-1044",
    attentionLevel: "decision",
    modality: "notification",
    summary: "Convert the replay incident into a reusable policy test.",
    whyNow: "The incident is fresh enough to encode a deterministic guardrail.",
    recommendation: "Promote the lesson after replay parity is verified.",
    decisionNeeded: false,
    alternatives: [
      { id: "alt-3", label: "Keep as shadow memory", effect: "wait for more evidence", risk: "low" },
      { id: "alt-4", label: "Promote now", effect: "teaches the policy kernel", risk: "medium" },
    ],
    riskDelta: { from: "medium", to: "low", note: "promotion lowers repeat incident risk" },
    drilldown: [{ label: "Open memory proposal", target: "memory.ML-220", kind: "memory" }],
    expires: "22m",
  },
];

export const voiceTextThreads: VoiceTextThread[] = [
  {
    id: "VT-41",
    channel: "voice",
    speaker: "telegram:user:42",
    title: "Approve deployment request",
    state: "confirmed",
    confidence: 0.97,
    transcript: "approve the deployment with token alpha",
    intent: "approval",
    confirmationPhrase: "alpha",
    requiresResponse: true,
    decisionOptions: ["approve", "deny"],
    updated: "2m ago",
    sourceRef: "voice.session.11111111-1111-4111-8111-111111111111",
  },
  {
    id: "VT-42",
    channel: "text",
    speaker: "telegram:user:42",
    title: "Deny bridge write lease",
    state: "transcribed",
    confidence: 0.93,
    transcript: "deny the bridge write lease",
    intent: "reject",
    requiresResponse: true,
    decisionOptions: ["deny", "approve"],
    updated: "11m ago",
    sourceRef: "voice.session.11111111-1111-4111-8111-111111111112",
  },
];

export const memoryLessons: MemoryProposal[] = [
  {
    id: "ML-219",
    scope: "adapter conformance",
    claim: "Adapters that emit raw webhooks stay quarantined until wrapped in JCP envelopes.",
    state: "proposed",
    confidence: 92,
    retention: "project",
    expiry: "7d",
    promotion: {
      status: "shadow",
      gate: "replay and evidence review",
    },
    counterexamples: [
      "Direct webhook handlers bypass policy.",
      "Silent retries can duplicate side effects.",
    ],
    source: "conformance.report",
    rollback: "Hold the adapter in read-only mode until the policy gate passes.",
    incident: {
      title: "Adapter quarantine still required",
      summary: "The bridge remains read-only until it has a service card.",
      quarantine: "Read-only",
      drilldown: ["Open adapter card", "Open replay evidence"],
    },
  },
  {
    id: "ML-220",
    scope: "release policy",
    claim: "Evidence gates need independent replay checks for schema promotion tasks.",
    state: "shadow",
    confidence: 81,
    retention: "long",
    expiry: "14d",
    promotion: {
      status: "proposed",
      gate: "advisory floor above threshold",
      reviewedBy: "jankurai",
    },
    counterexamples: ["A green smoke test is not enough without replay parity."],
    source: "replay.checkpoint",
    rollback: "Keep the lesson shadowed until replay parity proves the claim.",
  },
  {
    id: "ML-221",
    scope: "authority kernel",
    claim: "Direct credential access inside workers remains a policy violation even when tests pass.",
    state: "promoted",
    confidence: 98,
    retention: "long",
    expiry: "never",
    promotion: {
      status: "promoted",
      gate: "security review",
      promotedAt: "20m ago",
    },
    counterexamples: ["User-visible success does not override policy."],
    source: "security.finding",
    rollback: "This rule stays promoted and should not be removed.",
  },
];

export const replayEvents: ReplayEvent[] = [
  {
    sequence: 18421,
    subject: "work.WO-1042.task.schema",
    family: "TaskStateChanged",
    timestamp: "12:08:14Z",
    producer: "jmcpd",
  },
  {
    sequence: 18422,
    subject: "evidence.EV-731",
    family: "EvidenceAttached",
    timestamp: "12:08:21Z",
    producer: "jeryu",
  },
  {
    sequence: 18423,
    subject: "attention.approval.AP-88",
    family: "ApprovalRequested",
    timestamp: "12:09:02Z",
    producer: "policy-kernel",
  },
];

export const approvalRequests: ApprovalRequest[] = [
  {
    id: "AP-88",
    challengeId: "AP-88",
    workOrderId: "WO-1043",
    channel: "telegram",
    state: "pending",
    decision: "Approve bridge write-lease request",
    reason: "The bridge lacks C1 service-card evidence.",
    risk: "high",
    expires: "6m",
    approver: "telegram:user:42",
    tokenHash: "sha256:bridge-alpha",
    targetUserId: 42,
    targetChatId: 99,
    workOrderTitle: "Quarantine the MCP bridge until the service card is complete",
    workOrderState: "blocked",
    workOrderOwner: "adapter/mcp",
    currentTask: "Quarantine the MCP bridge until the service card is complete",
    branch: "jmcp/bridge-quarantine",
    pool: "telegram bot",
    placement: "jmcpd",
    voiceThreadId: "VT-41",
    voiceThreadState: "confirmed",
    voiceTranscript: "approve the deployment with token alpha",
    voiceConfirmationPhrase: "alpha",
    lineage: ["challenge.AP-88", "work.WO-1043", "voice.VT-41"],
  },
  {
    id: "AP-89",
    challengeId: "AP-89",
    workOrderId: "ML-221",
    channel: "local",
    state: "pending",
    decision: "Promote memory lesson ML-221",
    reason: "Lesson affects authority policy across all workers.",
    risk: "medium",
    expires: "22m",
    approver: "jankurai",
    tokenHash: "sha256:memory-221",
    workOrderTitle: "Promote memory lesson ML-221",
    workOrderState: "shadow",
    workOrderOwner: "jankurai",
    currentTask: "Promote memory lesson ML-221",
    branch: "policy/replay-ratchet",
    pool: "local",
    placement: "jmcpd",
    lineage: ["challenge.AP-89", "work.ML-221"],
  },
];
