import type { ControlPlaneSummary } from "./types";

export const controlPlane: ControlPlaneSummary = {
  generatedAt: "fixture",
  eventWatermark: 42,
  eventBus: {
    appendOnly: true,
    streamUrl: "/events",
    sources: ["runnerd", "agent_sessions", "ci_lanes", "audit_lanes"],
  },
  repos: [
    {
      name: "JMCP",
      health: "nominal",
      currentVersion: "0.1.0",
      lastSuccessfulMainCi: "sha256:ci-main",
      lastBinary: "sha256:jmcpd",
      lastTests: "sha256:test",
      latestChangedFiles: ["crates/jmcp-app/src/control_plane.rs"],
      activeWorkcells: 1,
      overdueActivity: false,
      stuckActivity: false,
      failingAudit: false,
      auditReason: null,
      rerunCommand: "just jankurai-local",
    },
    {
      name: "Jankurai",
      health: "watch",
      currentVersion: "0.1.0",
      lastSuccessfulMainCi: null,
      lastBinary: null,
      lastTests: "sha256:jankurai-proof",
      latestChangedFiles: ["agent/audit-policy.toml"],
      activeWorkcells: 1,
      overdueActivity: false,
      stuckActivity: false,
      failingAudit: true,
      auditReason: "No recent audit, CI, or proof evidence observed.",
      rerunCommand: "just score",
    },
  ],
  activeWorkcells: [
    {
      id: "jmcp-microtask-jankurai.changed-path-audit",
      repo: "Jankurai",
      agent: "jmcp.microtask_planner",
      task: "jankurai.diff-audit",
      status: "submitted",
      allowedSlice: ["Jankurai"],
      persistence: "pr_export_only",
      pty: "pty_disabled",
      updatedAt: "fixture",
      overdue: false,
      stuck: false,
      rerunCommand: "just score",
    },
  ],
  auditLanes: [
    {
      repo: "JMCP",
      lane: "jankurai.policy",
      health: "nominal",
      reason: "Latest audit evidence is visible to JMCP.",
      latestEvidence: "sha256:ci-main",
      rerunCommand: "just jankurai-local",
    },
    {
      repo: "Jankurai",
      lane: "jankurai.policy",
      health: "watch",
      reason: "No recent audit, CI, or proof evidence observed.",
      latestEvidence: null,
      rerunCommand: "just score",
    },
  ],
  policy: {
    sandboxRequired: true,
    directPersistenceAllowed: false,
    prExportRequired: true,
    ptyDefault: "disabled_unless_interactive",
    findingCount: 1,
  },
  versioning: {
    current: "0.1.0",
    recommended: "0.1.1",
    impact: "patch",
    reason: "Patch-safe evidence or maintenance work was observed.",
    releaseCompatible: true,
    rollbackCompatible: true,
  },
  streams: [
    {
      name: "jmcp.events",
      url: "/events",
      stdoutStderr: false,
      ptyInput: false,
      interactiveOnly: false,
    },
    {
      name: "session.stdout-stderr",
      url: "/jitux/sessions/:id/stream",
      stdoutStderr: true,
      ptyInput: false,
      interactiveOnly: false,
    },
    {
      name: "session.pty",
      url: "/jitux/sessions/:id/ws",
      stdoutStderr: true,
      ptyInput: true,
      interactiveOnly: true,
    },
  ],
};
